version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AppWoyofal
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - central_net

  nginx:
    image: nginx:latest
    container_name: woyofal_nginx_app
    ports:
      - "8060:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - central_net

 

networks:
  central_net:
    external: true
